# Generated by Django 4.1.3 on 2022-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
